### ISSUE TITLE
MOUSEBUTTON events instead of KEY events ()

### ISSUE THREAD

**Issue by amaendle** [kollokollo/X11Basic#13]
See line 1555 and 1556 in [https://github.com/kollokollo/X11Basic/blob/master/src/gkommandos.c](url):

` case SDL_KEYDOWN:`
`    if(e>0 && plist[0].typ!=PL_LEER) varcastint(plist[0].integer,plist[0].pointer,(event.type==SDL_KEYDOWN)?EVENT_MOUSEBUTTONPRESS:EVENT_MOUSEBUTTONRELEASE);`

Instead of `?EVENT_MOUSEBUTTONPRESS:EVENT_MOUSEBUTTONRELEASE);` this should be `?EVENT_KEYPRESS:EVENT_KEYRELEASE);`

**Comment by kollokollo** [comment]
Yep, good work! This looks like a bug.
