### ISSUE TITLE
KEYEVENT - reported character does not account for modifier keys

### ISSUE THREAD

**Issue by amaendle** [kollokollo/X11Basic#14]
This concerns the Windows/SDL platform.

`KEYEVENT kc,ks,t$,k,x,y,xroot,yroot`

after pressing "a", while holding the shift key I get

`print kc,ks,t$,k,x,y,xroot,yroot`
30      97      a       1       1       0       0       0

So the shift key is recognized. I expected t$='A' instead of 'a'.

**Comment by kollokollo** [comment]
What is the output without Shift? It could be a bug or maybe the WINDOWS implementation/version is not finished at this point. Need to look into the details of the SDL_KEYDOWN event type. As far as I can see, in t$ simply the single charackter from event.key.keysym.sym is returned. 

It looks like the SDL_library does not offer a function, which automatically modified the event.key.keysym.sym taking account the event.key.keysym.mod . (As fas as I can see at the moment). So you would need to translate it yourself. This is a bit strange, since there is the function SDL_GetKeyName, but this supposely returns a very strange Key name. See here: https://wiki.libsdl.org/SDL_Keycode

**Comment by amaendle** [comment]
The output ithout shift would be
`print kc,ks,t$,k,x,y,xroot,yroot`
30 97 a 0 1 0 0 0

**Comment by kollokollo** [comment]
So one could use the 4th parameter to convert the 3rd to uppercase. For other characters this would be more complicated.

**Comment by amaendle** [comment]
In [(that)](https://discourse.libsdl.org/t/2-0-4-get-char-from-keyboard-input/21775/5) it was claimed that `SDL_StartTextInput` should be used to get the character...  (BTW: Is X11 basic using SDL1 or SDL2?)

I guess it would be okay to do so: We could call SDL_StartTextInput()  in the keyevent function. Then check for both SDL_KEYDOWN and SDL_TEXTINPUT events. For SDL_TEXTINPUT you would probably have to return dummy values for kc and ks then, but I think that would be an okay solution.

If you don't want that, an alternative could be, to determine the character from the information in the SDL_Keysym. At least for Windows there is this solution: https://stackoverflow.com/questions/17386766/how-do-i-get-a-char-obtained-by-holding-shift

What do you think?

**Comment by kollokollo** [comment]
Ok, this could work, but it is more complicated to implement.  I would need C code (not C++).

**Comment by kollokollo** [comment]
I think I did it. tested this under wine. The AltGr Key does not work, but SHIFT and CAPS.

**Comment by amaendle** [comment]
wow, I'm impressed how much effort you put into this 👍 I'll test this probably later today or tomorrow.

**Comment by kollokollo** [comment]
It is more fun, if someone helps and especially test it under WINDOWS. ... Thanks!

**Comment by amaendle** [comment]
` The AltGr Key does not work, but SHIFT and CAPS.`

In Windows even the AltGr works! Also SHIFT and CAPS.

There is one more flaw with keyevent in Windows. The QWERTZ-keyboard layout isn't working for me. With the German and US keyboard layouts I get the same result, when I press the y-key on a QWERTZ keyboard:

`print kc,ks,t$,k,x,y,xr,yr`
44      122     z       0       1       0       0       0

The SDL_Keycode (in keyevent: ks) should be different for different keyboard mappings, only the SDL_SCANCODE (in keyevent: kc) should be unchanged.

**Comment by kollokollo** [comment]
Hm, do you think this is a bug in the SDL library? (Version SDL 1.x) in use. I am not sure, if the keycodes and scancodes returned by the SDL library are compatible with the WINDOWS native definitions (which I now use for mapping the charackters). 
Edit: Sorry, it is done differently: I use always the character returned by the SDL library (sym). Then ask for the Keycode, this character would be produced, and then do the mapping for this keycode. So a "z" should always be mapped to a "Z" (in theory) on any keyboard. But I cannot test this. So if you always get a "z" insead of a "y", then already the SDL-library has returned the wrong sym.

**Comment by amaendle** [comment]
It looks like a bug that was there in at least some (maybe all?) versions of SDL 1.x. However people have reported that  event.key.keysym.unicode returns the right symbol. I can't think of a good solution for now.

BTW: Is there a special reason why we are not using SDL 2 (I know.. many things changed from 1.2 to 2...)?

**Comment by amaendle** [comment]
We have at least the correct scancodes from SDL, I guess.

So maybe that will work: [nf-winuser-mapvirtualkeya](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-mapvirtualkeya) (yes, it's again a C++ example, again using winuser.h)

**Comment by kollokollo** [comment]
Maybe we then can use the scancode returned by SDL instaed of sym. (Maybe this is compatible with the new function GetModifiedKey.) So this line could be unnecessary: `sc = VkKeyScan(c);`

**Comment by kollokollo** [comment]
Why X11-Basic uses SDL version 1.x: 
Simply because 15 years ago, there only was (a single) version 1. And nobody has adapted the code for the new version so far. That's the reason. The WINDOWS version od X11-Basic was never prio no 1. In one other project (MQTT-Hyperdash) I have again used the SDL-Version (also for the linux version) and I think I got so confused that I decided to stay with the old SDL 1.2 again here, too. Maybe because it was not possible to install both versions for development on the same system. The use the same filenames etc. Since one project has used sdl 1.2 the others have to as well. (maybe I am wrong, but this was my belief so far).

**Comment by kollokollo** [comment]
It looks like the scan codes SDL returns do not help. I have not managed to map them to the WINDOWS "virtual key codes" correctly. So for now, I am giving up here.

**Comment by amaendle** [comment]
do you think the SDL scancodes are different than the Win32 API scancodes? That would make it more difficult indeed. I might look at it on the weekend, if I have time...

**Comment by kollokollo** [comment]
Yes, that is what it looks like: The SDL Scan codes are 1 for ESC and 2 for 1, etc, just enumerating the keys. However the Values returned by VkKeyScan(c) are of the form ASCII-Code of the charackter without modifiers in the low 8 bits and in the high 8 bits a bit for each pressed modifier key. So like the virtual key codes or sym (lower bits) returned by SDL. And the Function ToAscii always want these virtual key codes and not (real) scan codes. At least on my wine installation.

**Comment by kollokollo** [comment]
The original topic was fixed and is now in the master branch. The other issue:
" The QWERTZ-keyboard layout isn't working for me." is probably not yet fixed. Maybe we close this one and open another for this? What do you think?

**Comment by amaendle** [comment]
Nice work. I will have to check out your recent updates. 

I will close this and open a new issue as suggested.
