### ISSUE TITLE
after make install: libx11basic.so.1.27 not found

### ISSUE THREAD

**Issue by amaendle** [kollokollo/X11Basic#16]
When I try to execute `xbasic` in Fedora I get this error:
libx11basic.so.1.27: cannot open shared object file: No such file or directory

The log for make install was the following:
install -m 644 x11basic.svg /usr/local/share/icons/hicolor/scalable/apps/

install -m 644 x11basic.desktop /usr/local/share/applications/

install -s -m 755 xbasic /usr/local/bin/

install -s -m 755 fbxbasic /usr/local/bin/

install -m 755 ../examples/compiler/ybasic /usr/local/bin/

install -m 644 libx11basic.so.1.27 /usr/local/lib/

ln -s -f /usr/local/lib/libx11basic.so.1.27 /usr/local/lib/libx11basic.so.1

ln -s -f /usr/local/lib/libx11basic.so.1 /usr/local/lib/libx11basic.so

install -m 644 x11basic.a /usr/local/lib/

install -d /usr/local/share/man

install -d /usr/local/share/man/man1

install -m 644 doc/man-pages/x11basic.1 /usr/local/share/man/man1/x11basic.1

install -m 644 doc/man-pages/x11basic.1 /usr/local/share/man/man1/xbasic.1

install -m 644 doc/man-pages/ybasic.1   /usr/local/share/man/man1/ybasic.1

install -m 644 doc/man-pages/fbxbasic.1 /usr/local/share/man/man1/fbxbasic.1

install -s -m 755 xbc /usr/local/bin/

install -s -m 755 xb2c /usr/local/bin/

install -s -m 755 xbvm /usr/local/bin/

install -s -m 755 xbbc /usr/local/bin/

install -s -m 755 bas2x11basic /usr/local/bin/

install -d /usr/local/include/x11basic

install -m 644 x11basic.h /usr/local/include/x11basic/

install -m 644 xb2csol.h /usr/local/include/x11basic/

install -m 644 doc/man-pages/xbc.1 /usr/local/share/man/man1/

install -m 644 doc/man-pages/xbbc.1 /usr/local/share/man/man1/

install -m 644 doc/man-pages/xbvm.1 /usr/local/share/man/man1/

install -m 644 doc/man-pages/xb2c.1 /usr/local/share/man/man1/

install -m 644 doc/man-pages/bas2x11basic.1 /usr/local/share/man/man1/

**Comment by amaendle** [comment]
I did this:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

now it finally seems to work.

**Comment by kollokollo** [comment]
Yes. Sometimes also `sudo ldconfig` can do the job. It depends on the system configuration, wether /usr/local/ is in the default paths, I myself always install into /usr/, and thats also the installation place when you make a .deb file and install it from the debian package. if you want to make your own .deb file, you need to have installed checkinstall and then you can try a `make deb`.

**Comment by amaendle** [comment]
ok, thanks a lot. I think this can be closed, as I got it finally running in Fedora. I can now concentrate on finding more bugs.
