### ISSUE TITLE
Put_Bitmap: bug in SDL-version

### ISSUE THREAD

**Issue by amaendle** [kollokollo/X11Basic#17]
The windows/SDL version of Put_Bitmap does not match the description in the manual and the X11-version:

As the manual states, the correct behaviour is: _Each line must start on a new byte. So a 9x12 Bitmap stores in 24 Bytes._

Let _w_ denote the width of the image. Then the SDL-version (in function put_bitmap in window.c) expects the new line after exactly _w_ bits! - So, if _w_ is not a multiple of 8, the new line would start even in the middle of a byte.

I suppose it would not to hard to correct the code.

Also the GRAPHMODE has no effect in the SDL-version, but it does in Linux (X11).

**Comment by amaendle** [comment]
One more suggestion: In the bitmap RAW data I have from some old Atari Gfa-basic software, a new line usually starts at a multiple of 2 bytes. I think it would be a good idea to have an optional argument in put_bitmap, where you can set if the new lines start after a multiple of 1, 2 or 4 bytes. If you want to be compatible to GFA-basic I think a multiple of 2 bytes is the standard.

**Comment by kollokollo** [comment]
Yes, there is no corresponding graphics function in SDL for GRAPHMODE. SDL however can use the alpha channel. So in principle it would be possible to emulate it.

**Comment by kollokollo** [comment]
Looking into the code, i find (for bytes per line):

`int bpl=(w+1)>>3;`

So: 
w: 0...7 --> bpl=0
w: 7...14 --> bpl=1
... So this looks wrong. (can you confirm this)?

I think, this is how it should be:
`int bpl=(w>0?((w+1)>>3+1):0);`

Hm. Maybe: `int bpl=(w>0?(w>>3+1):0);`

**Comment by amaendle** [comment]
I'll check it out...

**Comment by kollokollo** [comment]
It was both wrong: Should be

` int bpl=(w>0?((w-1)>>3+1):0);`

**Comment by amaendle** [comment]
still does not seem to be correct... I'll try out sth more

**Comment by amaendle** [comment]
the parentheses were wrong:

`int bpl=(w>0?((w-1)>>3)+1:0);`

seems to do the trick

**Comment by kollokollo** [comment]
Ok, so this should now be in a commit in unstable. 
Having an extra parameter to define alignment is not necessary, I think. If you need Alignment to 16 bit, just adjust the width accordingly. 
Transparency would be a more serious problem. I read from your report, that this does not work. Am I right?

`GRAPHMODE 2` should do it. (Edit: sorry, it should be GRAPHMODE 2 for transparency). Does it work?

**Comment by amaendle** [comment]
> Having an extra parameter to define alignment is not necessary, I think. If you need Alignment to 16 bit, just adjust the width accordingly.

That's what I'm doing until now. However, I have to overwrite the dummy data in the unused bits when loading the data in X11-basic then. This is because the dummy data in the unused bits can be random.

> GRAPHMODE 2 should do it. 

You are right, GRAPHMODE 2 works. 

I hope we will also get GRAPHMODE 3 (and 4) working in SDL.
