### ISSUE TITLE
clearw fills always black instead of background color [SDL]

### ISSUE THREAD

**Issue by amaendle** [kollokollo/X11Basic#18]
The manual says: The Window is filled with the background color, which can be specified by COLOR.

In clearcw() in gkommandos.c we have:

#elif defined USE_SDL
      SDL_FillRect(window[winnr].display,NULL,0);

The 3rd parameter should specify a pixel with the background color.

**Comment by kollokollo** [comment]
Unfortunately it is not that simple. The third parameter expects the color in a different format, which would need conversion. If the color (32bit rgba) ia directly used, it looks like blue and red are reversed.

**Comment by amaendle** [comment]
> The color should be a pixel of the format used by the surface, and can be generated by the SDL_MapRGB or SDL_MapRGBA functions. [()](https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlfillrect.html)

I have dealt with that a long time ago for a project... I think I just extracted the pixel format of an [SDL_surface](https://www.libsdl.org/release/SDL-1.2.15/docs/html/sdlpixelformat.html) and used that as first parameter of SDL_MapRGB.

**Comment by kollokollo** [comment]
Yea. I am looking for a simple one-liner here. The background color is stored as a 32bit integer (it is RGBA but not documented) after the `COLOR` command. So is there a function which can extract the r,g,b components from it (to be used in  SDL_MapRGB)? Of course I simply can mask out these components from the color value, but this would be not portable.

**Comment by kollokollo** [comment]
I think this workaround should do it for now. (its a one-liner). If you can confirm, that it now works, we can close the issue...

**Comment by amaendle** [comment]
I'll test it later this week! Thanks for the update,

**Comment by amaendle** [comment]
It seems to work correctly, so I am closing this now!
