### ISSUE TITLE
mod expression requires parentheses

### ISSUE THREAD

**Issue by amaendle** [kollokollo/X11Basic#20]
In a program I have the following expression

`If (A% Mod 40=0)`

This if clause is not working in X11-Basic. 
After investigating a little, it seems that X11-Basic needs parentheses:

`print 166 mod 40 = 0`

returns -1.#IND

When I put extra parentheses, it works:

`print (166 mod 40) = 0`

returns 0

I suppose this is a bug. Otherwise, I would be happy to get an explanation.

**Comment by kollokollo** [comment]
Hm, yes. This comes from the fact, that any number modulo zero is undefined (gives a NaN = not a number). 
40=0 evaluates to zero (false). The MOD operator is of same rank than the AND OR XOR NOT etc. in X11-Basic. Do you think this should be different?
