### ISSUE TITLE
wrong ELF class: ELFCLASS32

### ISSUE THREAD

**Issue by sblendorio** [kollokollo/X11Basic#21]
I got the following error message when I execute "xbasic":

    xbasic: error while loading shared libraries: libusb-0.1.so.4: wrong ELF class: ELFCLASS32

I'm using Ubuntu 20, on x64 architecture. How could I solve that issue?
Thanks in advance

**Comment by kollokollo** [comment]
Hi sblendorio, Hm, something is wrong.
Have you compiled X11-Basic from sources or used a precompiled .deb package?
If you use the .deb packages (e.g. from here: https://codeberg.org/kollo/X11Basic/releases ) please use only the 
*_amd64.deb versions.

**Comment by kollokollo** [comment]
It might be a problem with the wron installation of libusb. 

If I do a 
<pre>
apt list --installed | grep libusb
</pre>
I get: 
<pre>
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libusb-0.1-4/focal,now 2:0.1.12-32 amd64  [installiert]
libusb-1.0-0/focal,now 2:1.0.23-2build1 amd64  [installiert]
libusb-1.0-0/focal,now 2:1.0.23-2build1 i386  [Installiert,automatisch]
libusbmuxd6/focal,now 2.0.1-2 amd64  [Installiert,automatisch]
</pre>

This means, the 32bit version is automatically installed and the other (correct) version needs to be installed manually: 

<pre>
sudo apt-get install libusb-1.0-0 libusb-0.1-4
</pre>

However, the easiest way would be to install
<pre>
sudo apt-get install libusb-dev
</pre>

this should automatically install the correct version.


Maybe this will help.

**Comment by sblendorio** [comment]
This solved:

    sudo apt-get install libusb-1.0-0 libusb-0.1-4
    sudo apt-get install libusb-dev

Thank you. Now I get this:
![image](https://user-images.githubusercontent.com/2118813/111504254-c3a91d00-8747-11eb-9291-774d67e36bb8.png)

is it correct?

**Comment by kollokollo** [comment]
Yes, thats it.
