### ISSUE TITLE
FSFIRST and FSNEXT work unexpectably.

### ISSUE THREAD

**Issue by ctzio** [kollokollo/X11Basic#25]
When you use FSFIRST and FSNEXT the string returned is in the form: 

"- filename.ext"
The workaround is to use REPLACE$(f$," -","") but I don't think this should be the expected behaviour.

**Comment by kollokollo** [comment]
This is intended: The first character is the file type. "-" means: regular file, "d" means directory. Use the SPLIT command to separate it (or WORD$())

**Comment by ctzio** [comment]
OK, I see. It took me way too long to find why my code isn't working :laughing:
