### ISSUE TITLE
Consider adding quit option

### ISSUE THREAD

**Issue by datacore-yirvine** [kollokollo/X11Basic#6]
(I am running the latest X11 version on debian stretch.)
I run from the shell:
`xbasic blah.bas`
At the end of the BASIC program, I am left in the xbasic prompt.
I would like to be dropped back to the shell.  I can achieve this by adding QUIT at the end of my program, but this is inconvenient, and easily missed if, e.g. there is a conditional exit in the middle of the program, for which I am used to using END, the classic BASIC command for exiting the program.  Or the code might not be mine, and it uses END to exit.
I would like to be able to do something like:
`xbasic -q blah.bas`
which would have the effect of quitting xbasic when the program ends.

**Comment by kollokollo** [comment]
Good point. OK, why not. Lets think of this as an improvement request. The commandline ooption -q is already used (for beeing quiet), but maybe -x (for exit at END).

**Comment by kollokollo** [comment]
I have implemented the new feature as 
--quitonend
It will totally omit the interactive mode and only run a given BASIC program The interpreter will terminate, when the PROGRAM ends.

The new feature is still on the "unstable" branch. To test it you would have to compile X11-Basic from that branch.
