### ISSUE TITLE
Keyboard issues on Android 9

### ISSUE THREAD

**Issue by Larsimusrex** [kollokollo/X11Basic#9]
When I use the console on my mobile phone (Moto g6; Android 9) console doesn't show what I tipping in when I type in Letter, any other Symbol works. I also can't delete words.

**Comment by kollokollo** [comment]
Hm, OK. Can you be more specific: What keyboard are you using (e.g. Hackers Keyboard?), Do you use any form of auto-completion? Language mode? Is the entered text shown after you have pressed Enter?

**Comment by Larsimusrex** [comment]
I'm just using Gboard whit autocompelete , I also tried MS swiftkey, which could delete, but still had the issue of not displaying the text. And yes the text becomes visible once I press any key, that is not a Letter.

**Comment by kollokollo** [comment]
OK, thank you, I assume, that you use the recent version 1.27 (from F-droid). I remember a similar issue some time ago, but I have forgot what to do.  I hope that the App can set a flag to tell the Keyboard not to behave like that. Need to investigate....

**Comment by kollokollo** [comment]
Is this still a problem with Version 1.28? Android 11 ?

**Comment by Larsimusrex** [comment]
I just tried it on my new Phone (Samsung galaxy a21 g5, Android 12) and I still had some issues, until I tried turning off text predictions at which point all issues disappeared.
